eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
 
 microservice:
  payment-service:
    uri: http://PAYMENT-SERVICE/payment/doPayment
 property-file.name=sanjay_jadhav
 property-file.description=hi_all
